#!/usr/bin/env bash
# Brightness handler using brightnessctl

CURRENT_BRIGHTNESS() { brightnessctl i | grep '%' | awk -F'(' '{print $2}' | awk -F'%' '{print $1}'; }

notify() {
    brightness="$(CURRENT_BRIGHTNESS)"
    
    if [ "$brightness" = "0" ]; then
        icon_name="notification-display-brightness-off"
    elif [ "$brightness" -lt "10" ]; then
        icon_name="notification-display-brightness-low"
    elif [ "$brightness" -lt "30" ]; then
        icon_name="notification-display-brightness-medium"
    elif [ "$brightness" -lt "70" ]; then
        icon_name="notification-display-brightness-medium"
    elif [ "$brightness" -lt "100" ]; then
        icon_name="notification-display-brightness-high"
    else
        icon_name="notification-display-brightness-full"
    fi
    ~/.scripts/notify/notify-send.sh -i "$icon_name" -t 1500 -r 1234 "$brightness "
}

case $1 in
    up)
        # +5%
        brightnessctl set 2%+ -q
        notify
	;;
    down)
        # -5%
        brightnessctl set 2%- -q
        notify
	;;
    optimal)
        # Toggle optimal
        brightnessctl set 25% -q
        notify
	;;
esac    
