#!/usr/bin/env bash
# Audio volume changer using alsa mixer

CURRENT_VOL() { amixer -D pulse get Master | grep '%' | head -n 1 | awk -F'[' '{print $2}' | awk -F'%' '{print $1}'; }
CHK_MUTE() { amixer -D pulse get Master | grep '%' | grep -oE '[^ ]+$' | grep off; }

notify() {
    volume="$(CURRENT_VOL)"
    
    if [ "$volume" = "0" ]; then
        icon_name="notification-audio-volume-muted"
    elif [  "$volume" -lt "10" ]; then
        icon_name="notification-audio-volume-low"
    elif [ "$volume" -lt "30" ]; then
        icon_name="notification-audio-volume-low"
    elif [ "$volume" -lt "70" ]; then
        icon_name="notification-audio-volume-medium"
    else
        icon_name="notification-audio-volume-high"
    fi
    notify-send.sh -i "$icon_name" -t 1500 -r 123 "$volume"
}

case $1 in
    up)
        amixer -D pulse set Master on -q
        # +5%
        amixer -D pulse sset Master 5%+ -q
        notify
	;;
    down)
        amixer -D pulse set Master on -q
        # -5%
        amixer -D pulse sset Master 5%- -q
        notify
	;;
    mute)
        amixer -D pulse set Master 1+ toggle -q
        if CHK_MUTE &> /dev/null; then
            icon_name="notification-audio-volume-muted"
            notify-send.sh -i "$icon_name" -t 1500 -r 123 "Muted "
        else
            notify
        fi
	;;
esac    
