#!/bin/sh
# Toggle touchpad status
# Using libinput and xinput

# Use xinput list and do a search for touchpads. Then get the first one and get its name.
DEVICE="$(xinput list | grep -P '(?<= )[\w\s:]*(?i)(focal|touchpad|synaptics)(?-i).*?(?=\s*id)' -o | head -n1)"
ICON="$HOME/.icons/linebit/keyboard.png"

# If it was activated disable it and if it wasn't disable it
# [[ "$(xinput list-props "$device" | grep -P ".*Device Enabled.*\K.(?=$)" -o)" == "1" ]] &&
#     xinput disable "$device" ||
#     xinput enable "$device"

if [[ "$(xinput list-props "$DEVICE" | grep -P ".*Device Enabled.*\K.(?=$)" -o)" == "1" ]]; then
    xinput disable "$DEVICE"
    notify-send.sh -t 1500 -i $ICON -r 123 "Deactivated"
else
    xinput enable "$DEVICE"
    notify-send.sh -t 1500 -i $ICON -r 123 "Actived"
fi
