#!/usr/bin/env bash
# Select window or draw and add borders then show preview
LC_ALL=C LANG=C; source $HOME/.scripts/screenshot/env

# SAVE_DIR=~/Pictures/scrot/draw

{
    rm -f /tmp/*_scrot*.png; read -rt ".5" <> <(:) || : 
    
    if scrot -q "${QUALITY:-75}" -sfbe 'mv $f /tmp/' -l style=dash,width=3,color="#6272a4" &> /dev/null; then
        notify-send.sh -t 500 -i $ICON -r 123 "scrot" "Processing captured image .."
    else
        notify-send.sh -t 500 -i $ICON -r 123 "scrot" "Screenshot canceled!" && exit 1
    fi
    
    for CURRENT in /tmp/*_scrot*.png; do
        CURRENT="$(echo $CURRENT | grep -oP '/tmp/\K[^.png]+' | sort -u)"
    done

    if [[ "$ENABLE_FRAME" = "yes" ]]; then
        convert /tmp/"$CURRENT".png \
        \( +clone -alpha extract -draw 'fill black polygon 0,0 0,8 8,0 fill white circle 8,8 8,0' \
        \( +clone -flip \) -compose Multiply -composite \( +clone -flop \) -compose Multiply -composite \) \
        -alpha off -compose CopyOpacity -composite /tmp/"$CURRENT"-rounded.png && rm -f /tmp/"$CURRENT".png

        convert /tmp/"$CURRENT"-rounded.png \( +clone -background black -shadow "${FRAMED_SHADOW_OPACITY:-25}"x10+0+5 \) \
        +swap -background none -layers merge +repage /tmp/"$CURRENT"-shadow.png && rm -f /tmp/"$CURRENT"-rounded.png

        convert /tmp/"$CURRENT"-shadow.png -bordercolor "${FRAME_COLOR:-#6272a4}" \
        -border 5 /tmp/"$CURRENT".png && rm -f /tmp/"$CURRENT"-shadow.png
    fi

    while true; do
        if [[ "$COPY2CLIP" = "yes" ]] && [[ -n "$(command -v "xclip")" ]]; then
            xclip -selection clipboard -target image/png -i /tmp/"$CURRENT".png
            STAT="\n(+CLIPBOARD)" && break
        elif [[ "$SAVE_SS" != "yes" ]]; then
            COPY2CLIP="yes"
        else break;
        fi
    done

    if [[ "$SAVE_SS" = "yes" ]]; then
        [[ ! -d "$SAVE_DIR/scrot/draw" ]] && mkdir -p "$SAVE_DIR/scrot/draw" || :
        mv /tmp/"$CURRENT".png "$SAVE_DIR/scrot/draw"
        SV_LOC="$(echo $SAVE_DIR | grep -oE '[^/]+$')/scrot/draw${STAT:-}"
    else
        rm -f /tmp/"$CURRENT".png
        SV_LOC="CLIPBOARD"
    fi

    notify-send.sh -i $ICON -u low "scrot" "Selected area has been captured!"

   if [[ -f "$SAVE_DIR/scrot/draw/$CURRENT.png" ]]; then
        [[ "$OPEN_FRAMED" = "yes" ]] && [[ -n "$(command -v "viewnior")" ]] && \
        viewnior "$SAVE_DIR/scrot/draw/$CURRENT.png"
    fi
} &> /dev/null &
