#!/usr/bin/env bash

# Music (mpd/spotify) controller

current="$(cat ~/.scripts/music-controller/default)"

if [[ $current == *"mpd"* ]]; then
    prev="mpc -q prev"
    toggle="mpc -q toggle"
    stop="mpc -q stop"
    next="mpc -q next"
    status="mpc status"
    title="$(mpc --format '[%title%|%file%]' current)"
elif [[ $current == *"spotify"* ]]; then
    prev="playerctl -p spotify previous"
    toggle="playerctl -p spotify play-pause"
    stop="playerctl -p spotify stop"
    next="playerctl -p spotify next"
    status="playerctl -p spotify status"
    title="$(playerctl -p spotify metadata -f '{{ artist }} - {{ title }}')"
else
    prev=""
    toggle=""
    stop=""
    next=""
    status=""
    title="There is no mpd or spotify installed"
fi
    
case $1 in
    icon)
    # For playback status on the panel
    if [[ $($status) == *"laying"* ]]; then
        if [[ $current == *"mpd"* ]]; then
            echo "$(mpc --format '[%title%|%file%]' current)"
         elif [[ $current == *"spotify"* ]]; then
            echo "$(playerctl -p spotify metadata -f '{{ artist }} - {{title}}')"
        fi
    else
        echo "Pause"
    fi
    ;;
    prev)
    bash -c "$prev"
    ;;
    toggle)
    
    bash -c "$toggle"
    ;;
    stop)
    bash -c "$stop" && notify-send.sh -u low -i "~/.icons/linebit/poweroff.png" -r 8888 "Music Player" "Stopped"
    ;;
    next)
    bash -c "$next"
    ;;
    title)
    # For song title on the panel
    echo "$title"
    ;;
    switchpl)
    # Switch music player between mpd and spotify
    if [[ $current == *"mpd"* ]]; then
        echo "spotify" > ~/.scripts/music-controller/default
    else
        echo "mpd" > ~/.scripts/music-controller/default
    fi
    notify-send.sh -u low -i "~/.icons/linebit/poweroff.png" -r 8888 "Music Player" "Set <b>`cat ~/.scripts/music-controller/default`</b> as default"
    ;;
esac