#!/usr/bin/env bash

SCRIPTPATH="$(cd "$(dirname "$0")" && pwd -P)"

# set background
if [ -x "$(command -v feh)" ]; then
	feh --bg-fill "$SCRIPTPATH"/down.jpg
fi

leftwm-command "UnloadTheme"

# kill procs
pkill greenclip
pkill polybar
pkill picom
pkill sxhk
pkill wired
