#!/usr/bin/env bash
export SCRIPTPATH="$(cd "$(dirname "$0")" && pwd -P)"

# down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
	/tmp/leftwm-theme-down
	rm /tmp/leftwm-theme-down
fi
ln -s "$SCRIPTPATH"/down /tmp/leftwm-theme-down

# set the theme.toml config
leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

# compositor
if [ -x "$(command -v picom)" ]; then
	picom &>/dev/null &
	# picom -b
fi

# notification
if [ -x "$(command -v wired)" ]; then
	wired &
fi

# set background
if [ -x "$(command -v feh)" ]; then
	feh --no-fehbg --bg-scale "$SCRIPTPATH"/kyoto_streets.png
fi

# cipboard manager
if [ -x "$(command -v greenclip)" ]; then
	greenclip daemon &
fi

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# status bar
if [ -x "$(command -v polybar)" ]; then
	index=0
	monitors="$(polybar -m | sed s/:.*//)"
	leftwm-state -q -n -t "$SCRIPTPATH"/sizes.liquid | sed -r '/^\s*$/d' | while read -r width x; do
		let indextemp=index+1
		monitor=$(sed "$indextemp!d" <<<"$monitors")
		barname="mainbar$index"
		monitor=$monitor offset=$x width=$width polybar -c "$SCRIPTPATH"/polybar/config.ini $barname &>/dev/null &
		let index=indextemp
	done
fi
