#!/usr/bin/env bash

# Brightness handler using brightnessctl

# set root privileges first if necessary
# sudo chmod u+s $(command -v brightnessctl)

current_brightness() {
	brightnessctl i | grep '%' | cut -d '(' -f 2 | cut -d '%' -f 1
}

notify() {
	brightness="$(current_brightness)"
	notify-send -r 2593 "   $brightness% "
}

case $1 in
--up)
	# +5%
	brightnessctl set 2%+ -q
	notify
	;;
--down)
	# -5%
	brightnessctl set 2%- -q
	notify
	;;
esac
