#!/usr/bin/env bash

# Audio volume changer using alsa mixer

current_vol() {
  amixer -D pulse get Master | grep '%' | head -n 1 | cut -d '[' -f 2 | cut -d '%' -f 1
}

is_mute() {
  amixer -D pulse get Master | grep '%' | grep -oE '[^ ]+$' | grep off
}

notify() {
  volume="$(current_vol)"

  if [ "$volume" -eq 0 ]; then
    icon=" "
  elif [ "$volume" -lt 50 ]; then
    icon=" "
  else
    icon=" "
  fi
  notify-send -r 2593 " $icon $volume% "
}

case $1 in
  --up)
    amixer -D pulse set Master on -q
    # +5%
    amixer -D pulse sset Master 5%+ -q
    notify
    ;;
  --down)
    amixer -D pulse set Master on -q
    # -5%
    amixer -D pulse sset Master 5%- -q
    notify
    ;;
  --mute)
    amixer -D pulse set Master 1+ toggle -q
    if is_mute &>/dev/null; then
      notify-send -r 2593 "   Muted! "
    else
      notify
    fi
    ;;
esac
