#!/usr/bin/env bash
# Take screenshot

SAVE_DIR=~/Pictures/Screenshots
ICON="~/.icons/custom/drops/files.png"

{
    [[ ! -e $SAVE_DIR ]] && mkdir $SAVE_DIR
    [[ $1 = "delay" ]] && sleep .5s
    scrot -ub -q 100 -e "mv '\$f' $SAVE_DIR" &> /dev/null
    notify-send -i $ICON -u low "Screenshot" "Saved in\n<u>$SAVE_DIR/</u>"
} &