#!/usr/bin/env bash
# Take screenshot after ..s

SAVE_DIR=~/Pictures/Screenshots
ICON="~/.icons/custom/drops/files.png"
TIMER_SEC="5"

{
    [[ ! -e $SAVE_DIR ]] && mkdir $SAVE_DIR
    notify-send -t 1000 -i $ICON -u low "Screenshot" "In $(echo $TIMER_SEC)s .."
    scrot -q quality 100 -d $TIMER_SEC -e "mv '\$f' $SAVE_DIR" &> /dev/null
    notify-send -i $ICON -u low "Screenshot" "Saved in\n<u>$SAVE_DIR/</u>"
} &
